### ISSUE TITLE
Proposta di modifica della struttura

### ISSUE THREAD

**Issue by ffranchina** [FabLabMessina/la_porta#2]
Ciao a tutti, ragazzi!!

Ho qui una proposta di semplificazione e potenziamento della struttura software per gestire la porta anche nell'ottica di una futura espandibilità.
## Vecchia proposta

Il vecchio design prevedeva tre strati: il **bridge** per comunicare con l'hardware, il **webserver** per esporre tutto sul web e l'**event manager** per gestire la comunicazione tra più sorgenti di informazioni.
Mentre a livello teorico sembrava tutto filare liscio, nella pratica della logica della programmazione veniva abbastanza ingarbugliato [(per questo non conviene mai scrivere di getto) ma neppure dopo tutte queste settimane...]!
Dove stava il problema? La struttura software che ne veniva fuori non favoriva l'espansibilità e avrebbe necessitato di certa manutenzione nel caso in cui avessimo voluto aggiungere qualche nuovo device e...
## Nuova proposta!

Mentre combattevo per strutturare il progetto in modo concettualmente _pulito_, ho deciso di rimettere tutto in discussione e di ripartire da zero. Bene, qual'è l'obiettivo? Avere un sistema nel quale posso modularmente aggiungere nuovi dispositivi e far si che questi vengano subito messi in comunicazione con altri tramite un sistema ad eventi e una logica personalizzata! Passo uno completato. Secondo passo: come dev'essere strutturato un dispositivo? Deve poter inviare/ricevere dati e generare eventi che possano essere gestiti dalla nostra logica personalizzata.
Ora tutto comincia a prendere forma: 
![schema software porta](https://cloud.githubusercontent.com/assets/8852116/11015493/2ecb5024-8561-11e5-8924-20ab870333cc.png)
Sebbene risulti immediatamente meno ordinata, concettualmente in realtà è molto più modulare e permette di gestire con trasparenza oggetti differenti.

Ecco la mia idea! Rifletteteci un po' anche voi e fatemi sapere cosa ne pensate. Se vi piace e non c'è altro da modificare, entro questa sera apro i vari task per comporre tutti insieme il progetto!

**Comment by rgsax** [comment]
Idea interessante, così ogni parte può essere sviluppata senza interferire con le altre

**Comment by fastlock** [comment]
sono d'accordo, é una soluzione piú elegante e funzionale

**Comment by ffranchina** [comment]
Ottimo, allora si procederà su questa strada! :)
